# Generated by Django 3.2.5 on 2021-08-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
    ]
